### ISSUE TITLE
wdio v7 is not supported

### ISSUE THREAD

**Issue by sergiocabreraoria** [jemishgopani/wdio-mochawesome-reporter#71]
This is not working running the latest version of wdio v7.10.0 with node v16.7.0 ... it should need to upgrade some dependencies

-  ```"@wdio/reporter": "^7.x.0",```
-  ```"@wdio/cli": "^7.x.0",```

**Issue**
![image](https://user-images.githubusercontent.com/58176975/130115450-56909f39-08ad-4239-ac32-81eee75cc528.png)

**Comment by JoanEsquivel** [comment]
I do have the same problem! :(

**Comment by bolem3560** [comment]
I also have same problem.  Could you please provide an update if any

**Comment by gromanas** [comment]
Hello! Actually, I have used it with wdio v7 and v6 and I haven't faced any issue so far. The issue when running the `npm i` is due to the: https://github.com/fijijavis/wdio-mochawesome-reporter/blob/6d812d46773bf8a6433bc3b1de067fc3aaa2b425/package.json#L50

Are there any plans for the reporter to be updated?

Thank you in advance!
