### ISSUE TITLE
Not working with wdio v8

### ISSUE THREAD

**Issue by bhanuagarwal73** [jemishgopani/wdio-mochawesome-reporter#84]
Can someone please fix for v8 ?

**Comment by jemishgopani** [comment]
@bhanuagarwal73 use this https://www.npmjs.com/package/wdio-mochajson-reporter

This has same configuration as previous mochawesome reporter

**Comment by gromanas** [comment]
Since it seems that this reporter also does not been supported anymore from @fijijavis. @christian-bromann Is there any chance to follow the same approach as for this reporter? https://github.com/fijijavis/wdio-json-reporter/issues/73. I can take over this.

**Comment by christian-bromann** [comment]
@gromanas I think it would be awesome if WebdriverIO would have a great html reporter option, unfortunately it seems like the mochaawesome project doesn't seem to be maintained much anymore. If we could find a great alternative that is build upon an existing html reporting framework I would be happy to add it to the core as e.g. `@wdio/html-reporter`. Can you make any recommendations?

**Comment by gromanas** [comment]
@christian-bromann Thank you very much for the quick reply. I was thinking about this and you are right. We were using `wdio-mochawesome-reporter` because it could export in json file where we were using it on a test results monitoring tool. A great alternative candidate could be `wdio-html-nice-reporter`, although we should check if this reporter has also the ability to export on json file (I think currently it doesn't, have to check), if not we can implement such a feature.

**Comment by jemishgopani** [comment]
@gromanas @christian-bromann @bhanuagarwal73 We published `wdio-mochawesome-reporter@6.1.0` for wdio v8 👍
